# Generated by Django 5.0.6 on 2024-06-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="логотип"
            ),
        ),
    ]
