# Generated by Django 5.0.6 on 2024-06-05 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_participationapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participationapplication",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participation_applications",
                to="main.course",
            ),
        ),
    ]
