# Generated by Django 5.0.6 on 2024-06-05 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_participationapplication_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="users",
            field=models.ManyToManyField(
                null=True, related_name="courses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
