# Generated by Django 5.0.6 on 2024-06-09 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_course_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Отзыв')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='аватар')),
                ('date', models.DateField()),
                ('user', models.ManyToManyField(null=True, related_name='reiting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
