# Generated by Django 5.0.6 on 2024-06-21 15:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reiting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reiting',
            options={'verbose_name': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='participationapplication',
            name='price',
        ),
        migrations.AlterField(
            model_name='participationapplication',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_applications', to='main.course', verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='participationapplication',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='participationapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='participationapplication',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='participationapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='participationapplication',
            name='wishes',
            field=models.TextField(blank=True, null=True, verbose_name='Оставьте комментарий'),
        ),
    ]
